source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADPPhotoPicker_Example', :exclusive => true do
    #pod "ADPPhotoPicker", :path => "../"
    pod 'ADPPhotoPicker', '~> 0.1.0'
end
