source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADPPhotoPicker_Example', :exclusive => true do
    #pod "ADPPhotoPicker", :path => "../"
    pod 'ADPPhotoPicker'
    #pod 'ADPPhotoPicker', :git => 'https://github.com/alexey-kubas-appus/ADPPhotoPicker.git'
end
