source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADPPhotoPicker_Example', :exclusive => true do
  pod "ADPPhotoPicker", :path => "../"
end

target 'ADPPhotoPicker_Tests', :exclusive => true do
  pod "ADPPhotoPicker", :path => "../"

  
end
